#define SPHSIMLIB_3D_SUPPORT
#define SPHSIMLIB_VEC_TYPE_FLOAT4
#define SPHSIMLIB_USE_TEXTURES
//#define SPHSIMLIB_USE_NEIGHBORLIST

//#define SPHSIMLIB_USE_CUDPP_SORT
//#define SPHSIMLIB_USE_THRUST_SORT
#define SPHSIMLIB_USE_B40C_SORT